### ISSUE TITLE
Add API V1 documentation

### ISSUE THREAD

**Issue by joshpuetz** [forem/forem-docs#87]
### Explain the changes

Documentation for Forem API V1 was recently added in PR https://github.com/forem/forem/pull/18187. We should add this documentation alongside the existing legacy V0 documentation on the Forem docs site.

**Comment by mirie** [comment]
Is this OK to close?

**Comment by mirie** [comment]
I'm wondering if it makes sense to change this to a milestone and add issues underneath it?

**Comment by joshpuetz** [comment]
That's a possibility! Ultimately though I don't anticipate having many _issues_ for this, just many _prs_.

**Comment by mirie** [comment]
How do you envision breaking up the work so that it is a gradual chipping away (will this be a task for anyone on the team to pick up or something that you will chip away at and thus creating issues is busy work?) -- if not issues then at least a quick task list? It's hard to know how we are making progress --- I think we initially discussed a goal of 2 endpoints a week, with an evaluation around 9/12/2022 to see if that was a reasonable goal

**Comment by joshpuetz** [comment]
Oh crap @mirie, I have to apologize: this issue refers to deploying the new V1 docs we wrote for the Negative Behavior Management APIs. The resolving PR (https://github.com/forem/forem-docs/pull/89) is currently blocked.

I never created an issue for recreating legacy V0 docs with rswag (I only have it as a task on this forgotten project board: https://github.com/orgs/forem/projects/65/)
